version: '3'

services:
    env:
        container_name: datys
        build: .
        ports:
            - "9111:9111"
        volumes:
            - ./src:/app/src
            - ./data:/app/data
        tty: true
